### ISSUE TITLE
tag?

### ISSUE THREAD

**Issue by liamstask** [brettlangdon/git-vendor#1]
Hi, thanks for putting this together, it's super helpful.

I was putting together a [homebrew](http://brew.sh) formula (based on [git-extras](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/git-extras.rb)), and its style audit prefers a formula to include a `stable` version.

Thought I'd check if you were planning to tag a revision as a preliminary release, otherwise I think I can just point it at the current revision in master. Thanks.

**Comment by brettlangdon** [comment]
@liamstask thanks! I just pushed `v1.0.0`, let me know if you need anything else.

**Comment by liamstask** [comment]
works for me - ty!

**Comment by liamstask** [comment]
submitted: https://github.com/Homebrew/homebrew/pull/49231

**Comment by brettlangdon** [comment]
Thanks @liamstask!
