### ISSUE TITLE
git vendor list does not update refs

### ISSUE THREAD

**Issue by AkhilGNair** [brettlangdon/git-vendor#11]
Hi, 

Essentially the problem I'm having is that if I
 - Vend a repo in
 - Update the vended repo on a feature branch
 - Squash merge the feature branch

The files are as expected, but `git vendor list` gives me the wrong `ref` and `commit`, (i.e. they don't get updated).  Is this a bug?  It doesn't block me at all, it's just a bit inconvenient to have the incorrect vendor details listed, when in this case I wanted the dependency updates only in the feature branch, until I pull the feature in.

Thanks for the extension + for any help,
Akhil

### Steps to reproduce issue

Sorry for the convoluted example.  Quite hard to make a good one as it involves pushing to a remote, but hopefully it illustrates the problem well enough

- Initialise 2 repos, `main_repo` and `side_repo`
 - Make a commit in `main_repo`
 - Make a commit in `side_repo`
 - Push `side_repo` to github
 - Run `git vendor add side git@github.com:AkhilNairAmey/side_repo.git` in `main_repo`

```
akhil@Sleek:~/scratch/vendor/main_repo (master)$ git vendor add side git@github.com:AkhilNairAmey/side_repo.git
+ git subtree add --prefix vendor/github.com/AkhilNairAmey/side_repo --message Add "side" from "git@github.com:AkhilNairAmey/side_repo.git@master"

git-vendor-name: side
git-vendor-dir: vendor/github.com/AkhilNairAmey/side_repo
git-vendor-repository: git@github.com:AkhilNairAmey/side_repo.git
git-vendor-ref: master
 git@github.com:AkhilNairAmey/side_repo.git master --squash
git fetch git@github.com:AkhilNairAmey/side_repo.git master
warning: no common commits
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From github.com:AkhilNairAmey/side_repo
 * branch            master     -> FETCH_HEAD
Added dir 'vendor/github.com/AkhilNairAmey/side_repo'
```

 - Make a change in side_repo, commit and push
 - Make a branch in `main_repo` called `feature`
```
akhil@Sleek:~/scratch/vendor/main_repo (master)$ git checkout -b feature
Switched to a new branch 'feature'
akhil@Sleek:~/scratch/vendor/main_repo (feature)$ git vendor list
side@master:
    name:   side
    dir:    vendor/github.com/AkhilNairAmey/side_repo
    repo:   git@github.com:AkhilNairAmey/side_repo.git
    ref:    master
    commit: 1cf8b9065db1b1268df2584f5332e5577d13b6eb
```

 - Update the vendored `side_repo`
```
 akhil@Sleek:~/scratch/vendor/main_repo (feature)$ git vendor update side
warning: no common commits
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From github.com:AkhilNairAmey/side_repo
 * branch            master     -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 vendor/github.com/AkhilNairAmey/side_repo/file2 | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 vendor/github.com/AkhilNairAmey/side_repo/file2
akhil@Sleek:~/scratch/vendor/main_repo (feature)$ git vendor list
side@master:
    name:   side
    dir:    vendor/github.com/AkhilNairAmey/side_repo
    repo:   git@github.com:AkhilNairAmey/side_repo.git
    ref:    master
    commit: 389b10df5f90646c6ce35bd913c04f83245f2a54  # Commit hash correct
```

 - Make another commit on `main_repo@master` to avoid fast-forward merge 
 - Squash merge feature back into branch
 ```
 akhil@Sleek:~/scratch/vendor/main_repo (master)$ git merge --squash feature 
Squash commit -- not updating HEAD
Automatic merge went well; stopped before committing as requested
```

 - Commit hash (or any other ref in more complex example) wrong, however files reflect the new repo state
```
akhil@Sleek:~/scratch/vendor/main_repo (master)$ git vendor list
side@master:
    name:   side
    dir:    vendor/github.com/AkhilNairAmey/side_repo
    repo:   git@github.com:AkhilNairAmey/side_repo.git
    ref:    master
    commit: 1cf8b9065db1b1268df2584f5332e5577d13b6eb  # Incorrect
```

**Comment by brettlangdon** [comment]
Hey, thanks for reporting. I am on vacation for the next month, but I'll be
sure to look at this as soon as I can. Sorry for any inconvenience.

**Comment by AkhilGNair** [comment]
Bump on this. Hope you had a good break :)

**Comment by brettlangdon** [comment]
Hey @AkhilNairAmey so sorry that I let this slip.

Yeah, this is to be expected since you are squash merging in your feature branch.

`git-vendor` tracks dependencies by using git commits (similar to the `git-subtree` commit messages).

You are updating the dependency on `feature`, which, `git vendor list` should work as expected, but then when you squash your feature branch and merge in you are removing the commit that is added by `git-vendor` so `git vendor list` will have issues looking up the correct information.

The reason this is an "issue" is that `git-vendor` uses `git-subtree` which, unlike `git-submodule`, doesn't keep track of the dependency's git repo, it just takes the remote repo, squashes it into one commit, and adds the files to your repo. After which `git-vendor` (and `git-subtree`) have to rely on the commit messages they create in order to track dependency versions/information.


Does that make sense?

**Comment by AkhilGNair** [comment]
Yup makes sense - so a normal merge won't have this issue?

**Comment by brettlangdon** [comment]
Correct, since it should preserve the commits created by `git-vendor`

**Comment by AkhilGNair** [comment]
No issue then! Thanks v much
